//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<System.TimeSpan> CheckIn { get; set; }
        public Nullable<System.TimeSpan> CheckOut { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
