//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfile
    {
        public int ProfileID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public string EducationLevel { get; set; }
        public string Experience { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
